table dim_carriers
	lineageTag: 5e14cab3-612f-43ff-9e30-79df3cb885b9

	column carrier_key
		dataType: string
		lineageTag: dd24c590-b5ac-49ce-8eda-7bbdd21c2808
		summarizeBy: none
		sourceColumn: carrier_key

		annotation SummarizationSetBy = Automatic

	column carrier_name
		dataType: string
		lineageTag: a056614e-e648-4b94-bb37-9fb2beb10f47
		summarizeBy: none
		sourceColumn: carrier_name

		annotation SummarizationSetBy = Automatic

	partition dim_carriers = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Users\Leonardo Martins\Documents\GitHub\loadsmart-techtest\powerbi\dim_carriers.csv"),[Delimiter=",", Columns=2, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"carrier_key", type text}, {"carrier_name", type text}})
				in
				  #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

